# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
heroku_username: heroku@weezlabs.com
heroku_password: heroku_email_sender

development:
  secret_key_base: 438a69a68ede010daae27a1cd22c305dc0f9065f7225916966dbb751ddbf037f224954193214caec2062b194b70dbc91333c93cf8bf0aae9bca528097db34129
  api_doc_username: "8L/2MmEJa@Au}ZZU"
  api_doc_password: "7z_jU>ap=<d~*h)g"
  facebook_app_id: '219375848396954'
  facebook_app_secret:  '4217cce0e703fb17f2dc4f8be65c9f14'


test:
  secret_key_base: e4e4b2448f5f0939d3deec2930027c49cfb47cace882df025b2689d1bc8736edd14603575191790b058dde79c01c1114af0e1a5a32a183ba6d25528a24fc2cb6

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_doc_username: "8L/2MmEJa@Au}ZZU"
  api_doc_password: "7z_jU>ap=<d~*h)g"
  facebook_app_id: '786533041490892'
  facebook_app_secret:  '33c7d62ccb65337bbb18384c3ed33210'


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
