source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'

gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes

#gem 'therubyracer', platforms: :ruby

gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml-rails', '~> 0.9.0'


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'swagger-docs'

gem 'swagger-ui_rails', :git => 'https://github.com/audionerd/swagger-ui_rails.git', :branch => "master"
gem 'rack-cors', :require => 'rack/cors'

gem 'acts-as-taggable-on'

gem 'aws-sdk', '~> 2'

gem 'versionist'
gem 'carrierwave'#, :github => 'satoruk/carrierwave' , :ref => '43179f94d6a4e62f69e812f5082d6447c9138480'
gem 'carrierwave_backgrounder'
gem 'rmagick'#, require: false

gem "fog-aws"
gem "fog"

gem 'rest-client', '~> 1.8'

gem 'doorkeeper'
# gem 'doorkeeper-grants_assertion', '~> 0.0.1'
gem 'devise'

# gem 'oauth2', '~> 1.0'
gem 'omniauth'
gem 'omniauth-facebook'


#search
gem 'pg_search', '~> 1.0', '>= 1.0.5'
# gem 'textacular', '~> 3.0'

#background jobs
gem 'delayed_job_active_record'
gem 'daemons'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # gem 'pry-rails'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # DRY logs
  gem 'quiet_assets'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
